local addr = "cd1e106a-8a84-4004-883c-4b993203fab7"
local drv = require("driver").getDriver("drive")
local nitro = dofile("A:/Fuchas/Filesystems/nitrofs.lua", drv)

xpcall(function()
	print("Formatting..")
	nitro.format()
	print("Done!")
	coroutine.yield()
	print("Creating directory \"/bin/\"..")
	nitro.makeDirectory("bin")
	print("Creating directory \"/lib/\"..")
	nitro.makeDirectory("lib")
	print("Creating directory \"/lib/nitro\"..")
	nitro.makeDirectory("lib/nitro")
	print("Creating file \"/test.txt\"..")
	local handle = nitro.open("test.txt", "w")
	print("Writing <512B data..")
	handle:write("Hello World!")
	print("Closing..")
	handle:close()
	print("File wrote!")
end, function(err)
	print(err)
	print(debug.traceback())
end)