# This is a basic workflow to help you get started with Actions

name: Dev release auto-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build CPIO
        run: |
          cd $GITHUB_WORKSPACE
          cd .efi/Source
          find . | cpio -oHbin > "../fuchas.efi2"
          cd ../..
          find Fuchas Users/Shared .efi | cpio -oHbin > "release.cpio"
          cd ..
      - name: Upload build
        uses: wei/curl@v1.1.1
        with:
          args: -X POST -F 'secret=$BUILD_SECRET' -F 'release=@release.cpio' https://bwsecondary.ddns.net/fuchas/upload_build.php
        env:
          BUILD_SECRET: ${{ secrets.BUILD_PUSH_KEY }}
